package newpackage;


import java.awt.Image;
import java.awt.Toolkit;
import static java.awt.Toolkit.getDefaultToolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nauman
 */
public class viewmasterinfo extends javax.swing.JFrame {

    /**
     * Creates new form viewmasterinfo
     */
    public viewmasterinfo() {
        initComponents();
   /*     Toolkit kt = Toolkit.getDefaultToolkit();
        
        int width = (int) kt.getScreenSize().getWidth();
        int height = (int) kt.getScreenSize().getHeight();
        
        this.setSize(width,height);
    */
        this.setBounds(250,150,1250,750);
        
        combobox.removeAllItems();
        String flag=null;
        combobox.addItem("All Department"); 
        table.setEnabled(false);
        try
        {
             DefaultTableModel model = new DefaultTableModel();
             
             model.addColumn("Id");
             model.addColumn("Name");
             model.addColumn("State");
             model.addColumn("City");
             model.addColumn("Date Of Joinig");
             model.addColumn("Salary");
             model.addColumn("Department");
             model.addColumn("Contact Number");
    
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fms","root","");
            Statement stmt = con.createStatement();
            ResultSet rs =stmt.executeQuery("select id,name,state,city,dateofjoining,salary,department,contactnumber from masterinfo");
            Statement stmt2 = con.createStatement();
            ResultSet rs2 =stmt2.executeQuery("select DISTINCT department from masterinfo");
            
            while(rs2.next())
            {
                combobox.addItem(rs2.getString("department"));
            }
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("id"),rs.getString("name"), rs.getString("state"), rs.getString("city"),rs.getString("dateofjoining"),rs.getString("salary"),rs.getString("department"),rs.getString("contactnumber")});
                
                
            }
            
            
            table.setModel(model);
            
            con.close();
        }
        
        catch(Exception e)
        {
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("fms?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        masterinfoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Masterinfo m");
        masterinfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : masterinfoQuery.getResultList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        headerlabel = new javax.swing.JLabel();
        idlable = new javax.swing.JLabel();
        idlable1 = new javax.swing.JLabel();
        idlable2 = new javax.swing.JLabel();
        idlable3 = new javax.swing.JLabel();
        idlable4 = new javax.swing.JLabel();
        idlable5 = new javax.swing.JLabel();
        idlable6 = new javax.swing.JLabel();
        idlable7 = new javax.swing.JLabel();
        idtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        statetf = new javax.swing.JTextField();
        citytf = new javax.swing.JTextField();
        dateofjoiningtf = new javax.swing.JTextField();
        salarytf = new javax.swing.JTextField();
        departmenttf = new javax.swing.JTextField();
        contactnumbertf = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        idprooflable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();
        searchbydepartmentbtnn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerlabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        headerlabel.setText("     View Employee's Information");
        headerlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        idlable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable.setText("Enter Master's Id :");

        idlable1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable1.setText("Name  :");

        idlable2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable2.setText("City :");

        idlable3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable3.setText("State : ");

        idlable4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable4.setText("Date Of Joining :");

        idlable5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable5.setText("Salary :");

        idlable6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable6.setText("Department :");

        idlable7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idlable7.setText("Contact Number :");

        idtf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        nametf.setEditable(false);
        nametf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        statetf.setEditable(false);
        statetf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        citytf.setEditable(false);
        citytf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        dateofjoiningtf.setEditable(false);
        dateofjoiningtf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        salarytf.setEditable(false);
        salarytf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        departmenttf.setEditable(false);
        departmenttf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        contactnumbertf.setEditable(false);
        contactnumbertf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        searchbtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        resetbtn.setText("Reset Record");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/home icon - Copy.png"))); // NOI18N
        jButton1.setText("Go To Home");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idprooflable.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        idprooflable.setText("                 Id Proof Will Appear Here");
        idprooflable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table);

        combobox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchbydepartmentbtnn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        searchbydepartmentbtnn.setText("Search by Department");
        searchbydepartmentbtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbydepartmentbtnnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(idlable7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(contactnumbertf, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(idlable6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idlable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(idlable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(salarytf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                            .addComponent(dateofjoiningtf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(citytf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(statetf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nametf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idtf, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(departmenttf))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchbydepartmentbtnn))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(175, 175, 175)
                                            .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(idprooflable, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchbtn)
                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nametf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statetf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(citytf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateofjoiningtf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salarytf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlable6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmenttf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactnumbertf)
                            .addComponent(idlable7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idprooflable, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbydepartmentbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        
        int count=0;
        
        try
        {
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fms","root","");
            
            Statement stmt = con.createStatement();
            
            ResultSet rs =stmt.executeQuery("select name,state,city,dateofjoining,salary,department,contactnumber,image from masterinfo where id = "+idtf.getText());
            
            
            
            while(rs.next())
            {
                count++;
                
                nametf.setText(rs.getString("name"));
                statetf.setText(rs.getString("state"));
                citytf.setText(rs.getString("city"));
                dateofjoiningtf.setText(rs.getString("dateofjoining"));
                salarytf.setText(rs.getString("salary"));
                departmenttf.setText(rs.getString("department"));
                contactnumbertf.setText(rs.getString("contactnumber"));
            }
            
            byte[] imagebytes;
            Image myimage;
            
            PreparedStatement ps;
            ps = con.prepareStatement("select image from masterinfo where id = ?");
            
            int id = Integer.parseInt(idtf.getText());
            
            ps.setInt(1, id);
            
            ResultSet rs2 = ps.executeQuery();
            
            while(rs2.next())
            {
                imagebytes = rs2.getBytes("image");
                myimage = getDefaultToolkit().createImage(imagebytes);
            //    ImageIcon icon2 = new ImageIcon(myimage);
                ImageIcon icon2 = new ImageIcon(new ImageIcon(myimage).getImage().getScaledInstance(idprooflable.getWidth(), idprooflable.getHeight(),Image.SCALE_DEFAULT));
                idprooflable.setText("");
                idprooflable.setIcon(icon2);
            }
            
           con.close();
          
           
           if(count==0)
           {
               JOptionPane.showMessageDialog(this,"!! Record not Found !!");
           }
        }
        
        catch(Exception e)
        {
            
        } 
    }//GEN-LAST:event_searchbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        idprooflable.setIcon(null);
        nametf.setText("");
        statetf.setText("");
        citytf.setText("");
        dateofjoiningtf.setText("");
        salarytf.setText("");
        departmenttf.setText("");
        contactnumbertf.setText("");
        idtf.setText("");
        
    }//GEN-LAST:event_resetbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        masterinfohome homeobj = new masterinfohome();
        homeobj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchbydepartmentbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbydepartmentbtnnActionPerformed
        // TODO add your handling code here:
    try
    {
        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("Id");
        model2.addColumn("Name");
        model2.addColumn("State");
        model2.addColumn("City");
        model2.addColumn("Date Of Joinig");
        model2.addColumn("Salary");
        model2.addColumn("Department");
        model2.addColumn("Contact Number");
        
        
  
        Class.forName("com.mysql.jdbc.Driver");
        Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/fms","root","");
       
       if(combobox.getSelectedItem().equals("All Department"))
       {
           Statement stmt3 = con2.createStatement(); 
           ResultSet rs3 =stmt3.executeQuery("select id,name,state,city,dateofjoining,salary,department,contactnumber from masterinfo");
           while(rs3.next())
            {
                model2.addRow(new Object[]{rs3.getString("id"),rs3.getString("name"), rs3.getString("state"), rs3.getString("city"),rs3.getString("dateofjoining"),rs3.getString("salary"),rs3.getString("department"),rs3.getString("contactnumber")});
                
                
            }
       }    
       
       else
       {
           PreparedStatement stmt;
           stmt = con2.prepareStatement("select id,name,state,city,dateofjoining,salary,department,contactnumber from masterinfo where department = ?");
        
           stmt.setString(1, (String) combobox.getSelectedItem());
        
           ResultSet rs2 = stmt.executeQuery();
        
            while(rs2.next())
            {
                model2.addRow(new Object[]{rs2.getString("id"),rs2.getString("name"), rs2.getString("state"), rs2.getString("city"),rs2.getString("dateofjoining"),rs2.getString("salary"),rs2.getString("department"),rs2.getString("contactnumber")});
                
                
            }
       }
       
        con2.close();
    
        table.setModel(model2);
    }
    
    catch(Exception e)
    {
        
    }
    
        
             
 
    
               
    }//GEN-LAST:event_searchbydepartmentbtnnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewmasterinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewmasterinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewmasterinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewmasterinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewmasterinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField citytf;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField contactnumbertf;
    private javax.swing.JTextField dateofjoiningtf;
    private javax.swing.JTextField departmenttf;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel idlable;
    private javax.swing.JLabel idlable1;
    private javax.swing.JLabel idlable2;
    private javax.swing.JLabel idlable3;
    private javax.swing.JLabel idlable4;
    private javax.swing.JLabel idlable5;
    private javax.swing.JLabel idlable6;
    private javax.swing.JLabel idlable7;
    private javax.swing.JLabel idprooflable;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private java.util.List<newpackage.Masterinfo> masterinfoList;
    private javax.persistence.Query masterinfoQuery;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField salarytf;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton searchbydepartmentbtnn;
    private javax.swing.JTextField statetf;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
